{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "76e60627",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd  # pip install pandas openpyxl\n",
    "import plotly.express as px  # pip install plotly-express\n",
    "import streamlit as st  # pip install streamlit\n",
    "\n",
    "# emojis: https://www.webfx.com/tools/emoji-cheat-sheet/\n",
    "st.set_page_config(page_title=\"PNBP PPPK\", page_icon=\":bar_chart:\", layout=\"wide\")\n",
    "\n",
    "# ---- READ EXCEL ----\n",
    "@st.cache\n",
    "def get_data_from_excel():\n",
    "    df = pd.read_excel(\n",
    "        io=\"Rekap PNBP September 2021.xlsx\",\n",
    "        engine=\"openpyxl\",\n",
    "        sheet_name=\"Rekapitulasi Denda PNBP\",\n",
    "        #skiprows=3,\n",
    "        usecols=\"A:D\",\n",
    "        nrows=136,\n",
    "    )\n",
    "    df.dropna(inplace=True) \n",
    "    # Add 'hour' column to dataframe\n",
    "    # df[\"hour\"] = pd.to_datetime(df[\"Time\"], format=\"%H:%M:%S\").dt.hour\n",
    "    return df\n",
    "\n",
    "df = get_data_from_excel()\n",
    "\n",
    "df1 = pd.read_excel(\n",
    "    \"Rekap PNBP September 2021.xlsx\",\n",
    "    sheet_name=\"Rekapitulasi Denda PNBP\",\n",
    "    #skiprows=3,\n",
    "    usecols=\"A:F\",\n",
    "    nrows=136, \n",
    ")\n",
    "        \n",
    "# ---- SIDEBAR ----\n",
    "st.sidebar.header(\"Silahkan Pilih Jenis PNBP:\")\n",
    "pnbp = st.sidebar.selectbox(\n",
    "    \"\",\n",
    "    df[\"Jenis_PNBP\"].unique()\n",
    ")\n",
    "\n",
    "#OAA = st.sidebar.multiselect(\n",
    "    #\"OAA:\",\n",
    "    #options=df[\"KAPA_atau_OAA\"].unique(),\n",
    "    #default=df[\"KAPA_atau_OAA\"].unique(),\n",
    "#)\n",
    "\n",
    "#OAI = st.sidebar.multiselect(\n",
    "    #\"OAI:\",\n",
    "    #options=df[\"OAI\"].unique(),\n",
    "    #default=df[\"OAI\"].unique()\n",
    "#)\n",
    "\n",
    "df_selection = df.query(\n",
    "    \"Jenis_PNBP == @pnbp\"\n",
    ")\n",
    "\n",
    "# ---- MAINPAGE ----\n",
    "st.title(\":bar_chart: PNBP Satker PPPK Tahun 2021\")\n",
    "st.markdown(\"##\")\n",
    "\n",
    "# TOP KPI's\n",
    "total_denda = int(df_selection[\"Rupiah\"].sum())\n",
    "#average_rating = round(df_selection[\"Rating\"].mean(), 1)\n",
    "#star_rating = \":star:\" * int(round(average_rating, 0))\n",
    "rata_denda = int(df_selection[\"Rupiah\"].mean())\n",
    "\n",
    "left_column, middle_column, right_column = st.columns(3)\n",
    "with left_column:\n",
    "    st.subheader(\"Jumlah PNBP:\")\n",
    "    st.subheader(f\"Rp {total_denda:,}\")\n",
    "#with middle_column:\n",
    "    #st.subheader(\"Average Rating:\")\n",
    "    #st.subheader(f\"{average_rating} {star_rating}\")\n",
    "with right_column:\n",
    "    st.subheader(\"Rata-rata PNBP:\")\n",
    "    st.subheader(f\"Rp {rata_denda:,}\")\n",
    "\n",
    "st.markdown(\"\"\"---\"\"\")\n",
    "\n",
    "# SALES BY PRODUCT LINE [BAR CHART]\n",
    "sales_by_product_line = (\n",
    "    df_selection.groupby(by=[\"Bulan\"]).sum()[[\"Rupiah\"]].sort_values(by=\"Rupiah\")\n",
    ")\n",
    "fig_product_sales = px.bar(\n",
    "    sales_by_product_line,\n",
    "    x=sales_by_product_line.index,\n",
    "    y=\"Rupiah\",\n",
    "    #orientation=\"h\",\n",
    "    title=\"<b>Jumlah PNBP</b>\",\n",
    "    color_discrete_sequence=[\"#0083B8\"] * len(sales_by_product_line),\n",
    "    template=\"plotly_white\",\n",
    "    #width = 800,\n",
    "    #height = 600,\n",
    ")\n",
    "fig_product_sales.update_layout(\n",
    "    plot_bgcolor=\"rgba(0,0,0,0)\",\n",
    "    xaxis=(dict(showgrid=False))\n",
    ")\n",
    "\n",
    "#st.plotly_chart(fig_product_sales)\n",
    "\n",
    "# SALES BY KODE BILING [BAR CHART]\n",
    "sales_by_kode_biling = (\n",
    "    df_selection.groupby(by=[\"Bulan\"]).sum()[[\"Satuan\"]].sort_values(by=\"Satuan\")\n",
    ")\n",
    "fig_kode_biling = px.bar(\n",
    "    sales_by_kode_biling,\n",
    "    x=sales_by_kode_biling.index,\n",
    "    y=\"Satuan\",\n",
    "    #orientation=\"h\",\n",
    "    title=\"<b>Jumlah Kode Biling</b>\",\n",
    "    color_discrete_sequence=[\"#0083B8\"] * len(sales_by_kode_biling),\n",
    "    template=\"plotly_white\",\n",
    "    #width = 1000,\n",
    "    #height = 600,\n",
    ")\n",
    "fig_kode_biling.update_layout(\n",
    "    plot_bgcolor=\"rgba(0,0,0,0)\",\n",
    "    xaxis=(dict(showgrid=False))\n",
    ")\n",
    "\n",
    "#st.plotly_chart(fig_kode_biling)\n",
    "\n",
    "# SALES BY HOUR [BAR CHART]\n",
    "#sales_by_hour = df_selection.groupby(by=[\"Big_4\"]).sum()[[\"Fee_Jasa\"]]\n",
    "#fig_hourly_sales = px.bar(\n",
    "    #sales_by_hour,\n",
    "    #x=sales_by_hour.index,\n",
    "    #y=\"Fee_Jasa\",\n",
    "    #title=\"<b>Big 4</b>\",\n",
    "    #color_discrete_sequence=[\"#0083B8\"] * len(sales_by_hour),\n",
    "    #template=\"plotly_white\",\n",
    "#)\n",
    "#fig_hourly_sales.update_layout(\n",
    "    #xaxis=dict(tickmode=\"linear\"),\n",
    "    #plot_bgcolor=\"rgba(0,0,0,0)\",\n",
    "    #yaxis=(dict(showgrid=False)),\n",
    "#)\n",
    "\n",
    "\n",
    "left_column, right_column = st.columns(2)\n",
    "left_column.plotly_chart(fig_product_sales, use_container_width=True)\n",
    "right_column.plotly_chart(fig_kode_biling, use_container_width=True)\n",
    "\n",
    "st.markdown(\"\"\"---\"\"\")\n",
    "\n",
    "# PERHITUNGAN PERSENTASE PNBP\n",
    "total_pnbp = int(df1[\"Rupiah\"].sum())\n",
    "target_pnbp = round(df1.iloc[0, 5])\n",
    "x = total_pnbp / target_pnbp \n",
    "persen_pnbp = str(round(x*100)) + '%'\n",
    "st.subheader(f\"Total PNBP: {total_pnbp:,}\")\n",
    "st.subheader(f\"Target PNBP: {target_pnbp:,}\")\n",
    "st.subheader(f\"Persentase PNBP: {persen_pnbp}\")\n",
    "#target_pnbp = int(df1[\"Target\"].sum())\n",
    "#df1.dropna(inplace=True)\n",
    "\n",
    "# ---- HIDE STREAMLIT STYLE ----\n",
    "hide_st_style = \"\"\"\n",
    "            <style>\n",
    "            #MainMenu {visibility: hidden;}\n",
    "            footer {visibility: hidden;}\n",
    "            header {visibility: hidden;}\n",
    "            </style>\n",
    "            \"\"\"\n",
    "st.markdown(hide_st_style, unsafe_allow_html=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
